apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: loki
spec:
  ingressClassName: nginx
  rules:
    - host: ${INGRESS_IP}.grafana.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-grafana
                port:
                  number: 80
