apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-grafana
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${INGRESS_IP}.sslip.io
      secretName: app-tls-secret
  rules:
    - host: ${INGRESS_IP}.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-external
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 8080