apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - ${INGRESS_IP}.sslip.io
      secretName: app-tls-secret
  rules:
    - host: ${INGRESS_IP}.sslip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-external
              port:
                number: 80
