{
 "title": "Приложение",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{namespace=\"app\", pod!=\"\"}[5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace, pod, container) (rate(container_memory_usage_bytes{namespace=\"app\", pod!=\"\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Errors в Приложении",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"app\"} |= `error` [1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Warnings в Приложении",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"app\"} |= `warning` [1h])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ошибки по эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method, path) (\n  rate({namespace=\"app\"}\n  | json\n  | line_format \"{{.log}}\"\n  | regexp \"(?P<method>GET|POST)\\\\s+(?P<path>/\\\\S*)\\\\s+\\\\d+\\\\s+(?P<errors>\\\\d+)\\\\(\"\n  | unwrap errors [5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Скорость появления errors/warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (severity) (\n  rate({namespace=\"app\"}\n  | json\n  | line_format \"{{.log}}\"\n  | json\n  | severity=~\"(error|warn)\" [5m])\n)"
    }
   ]
  },
  {
   "title": "Количество логов в секунду (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate({namespace=\"app\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Логи Приложения",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"app\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}