{
 "title": "Инфраструктура",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage Seconds Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{namespace!=\"app\", pod!=\"\"}[5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace, pod, container) (rate(container_memory_usage_bytes{namespace!=\"app\", pod!=\"\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network receive Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\n  rate(container_network_receive_bytes_total{namespace!=\"app\"}[5m])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FS Usage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace, pod) (\n  container_fs_usage_bytes{namespace!=\"app\"}\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Логи Инфраструктуры",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace!=\"app\", pod!=\"\"}"
    }
   ]
  }
 ]
}