apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argo-cd
spec:
  project: otus
  source:
    repoURL: https://github.com/D1987/otus-project.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true