controller:
  service:
    type: LoadBalancer
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  nodeSelector:
    role: infra
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
