# Ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io/background
spec:
  project: infra-project
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.2
  - repoURL: https://github.com/D1987/otus-project.git
    targetRevision: project
    ref: values-repo
    helm:
      releaseName: ingress-nginx
      valueFiles:
        - $values-repo/helm-values/ingress-nginx/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
# Cert-manager
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io/background
spec:
  project: infra-project
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.4
  - repoURL: https://github.com/D1987/otus-project.git
    targetRevision: project
    ref: values-repo
    helm:
      releaseName: cert-manager
      valueFiles:
        - $values-repo/helm-values/cert-manager/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Monitoring
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io/background
spec:
  project: infra-project
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 3.5.0
  - repoURL: https://github.com/D1987/otus-project.git
    targetRevision: project
    ref: values-repo
    helm:
      releaseName: loki-stack
      valueFiles:
        - $values-repo/helm-values/monitoring/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true